### ISSUE TITLE
Required validation for signature

### ISSUE THREAD

**Issue by harikrishna149** [brinley/jSignature#102]
Hi,

I am working with jSignature in my application using asp.net mvc angularjs. I want to do vallidate this signature as required. 
I tried using getdata method when canvas is empty and i get the signature length is 2430. how can i validate the signature. please help me asap.

Code:
$scope.saveSignature = function () {
        var data = $("#signature").jSignature("getData");
        alert(data.length);
        $scope.SignData = sig.jSignature('getData');
    }

I want to validate the signature in saveSignature  function. Please help me

**Comment by brinley** [comment]
Try using ismodified to check if the canvas has any content

**Comment by harikrishna149** [comment]
Hi,
 I checked the canvascontent using ismodified but i didn't get any solution. i got undefined as alert message.

the code looks like
$scope.saveSignature = function () {
        var data = $("#signature").jSignature("isModified");
        alert(data.length);
        $scope.SignData = sig.jSignature('getData');
    }

**Comment by brinley** [comment]
getData on a canvas will always return data even for a blank canvas. Perhaps you can save the data for your blank canvas and use that to compare if there is any content.

**Comment by peerles** [comment]
Why not use the method like this: '$sigdiv.jSignature('getData', 'native').length'?
if the length is 0, then the canvas has no content, else the canvas has any content
and the lenth is eauals to the number of strokes
