### ISSUE TITLE
Convert base30 format 

### ISSUE THREAD

**Issue by aspcsharp** [brinley/jSignature#105]
Hi,

In my database stay base30 format, now I need convert that to svg or base64.

Here is my example with error any solution?

http://prnt.sc/afz8yn

**Comment by javedofhumber** [comment]
Hi..can u please help me in the same. I am trying to save the data in base30 format, but I have no clue how to display them after retrieving the data from the database, neither the class library in the extra folder is helping I used ur code from the example but still no help. If you can help me with this issues, it will be a great favour. Thanks

**Comment by brinley** [comment]
Have a look at the .Net converters at https://github.com/brinley/jSignature/tree/master/extras/SignatureDataConversion_dotNet/core

**Comment by javedofhumber** [comment]
Hi,
I tried using all these, but it didnt helped
