### ISSUE TITLE
SignatureDataConversion_dotNet cause wrong assembly information on ASP.NET Core projects.

### ISSUE THREAD

**Issue by LukaszDev** [brinley/jSignature#113]
Hi @brinley,

**SignatureDataConversion_dotNet** can cause [wrong assembly information on ASP.NET Core projects, dotnet/cli #3620](https://github.com/dotnet/cli/issues/3620).

This is because SignatureDataConversion_dotNet project contains `AssemblyInfo.cs` and when I add jSignature to my project (via Bower) then by default Visual Studio treat this file like as part of my project...

By default ASP.NET Core projects don't include `AssemblyInfo.cs` and necessary meta data are taken from `project.json`.

So, when I add jSignature to my project (via Bower) then `AssemblyInfo.cs` file form jSignature is in use by Visual Studio.

Of course there is solution for this, but still it can make confusion for developers who don't know about that

Will be great if we can sort this on jSignature level ?

My suggestions how to deal with `SignatureDataConversion_dotNet`:

 - archive this project and store it as ZIP file (all extras can be stored as ZIP),
 - remove it form jSignature bower package (looks like old project), and put it as external download,
 - upgrade project to VS2015 / .NET Core without `AssemblyInfo.cs` (currently it's VS2008 / .NET Framework 2.0 project).

What do you thing about that ?

**Comment by brinley** [comment]
I like the third choice of upgrading the VS project. 
Do you know if this would cause any other issues?
If not, can you please submit a PR?
Thanks

**Comment by LukaszDev** [comment]
>Do you know if this would cause any other issues?

I'm not sure yet - should be fine form general perspective... I will check this.

However this is 'one way' upgrading, so it will be a problem for developers with older VS like as VS2012/2013 (still in use). They will be not able to directly open solution/project.

Of course still code will be directly accessible, so always you can create new project and just import specific class with code - it shouldn't be a big issue.

**Comment by LukaszDev** [comment]
O, looks like migration to VS2015 / .NET Core is ok.

Project is compiled successfully and all NUnit tests are passed - however I have no knowledge about this logic, so I can't verify it.

I have use all original code - with small modification in test project (to get path to samples files).

Unfortunately I have no time to deeply test it - @brinley is this ok for you ?

Is there any one who, know more about this and can test it more? 

<br>
@brinley, last thing - any special title / description / copyright / version ?

As for now I set:
```
title: SignatureDataConversion.Core / SignatureDataConversion.Tests
description: jSignature Tools
copyright: Copyright © 2016 by jSignature
version: 2.0.0-*
```

**Comment by LukaszDev** [comment]
Ok, I will update this over weekend

**Comment by LukaszDev** [comment]
> For the version, perhaps we should increment the minor version number

 - old version for _SignatureDataConversion_ is `1.0.0.0`,
 - _jSignature_ is currently `2.0.2`,

Please advise me what version exactly you want set ?

Please note: there is no changes in core code, however project was migrated to new (not backward compatible) version... so, we can consider this as 'breaking changes' ?

<br>
I don't have too much experience with 'not my own' repos - should I make next pull request or there is something else to do ?
