### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by LukaszDev** [brinley/jSignature#119]
Hi Brinley,

Could you create new release to reflect recent changes (touch-action: none and fix for SignatureDataConversion_dotNet), please ?

Current release is v2.0.2 form 2014 ;)

Thank you in advance :)

<br>
BTW: Bower versioning is base on GitHub release/tags, and version field is deprecated, so you can remove it form `bower.json` - it's make releasing little bit easier for the future.

 - [bower.json specification](https://github.com/bower/spec/blob/master/json.md#bowerjson-specification)
 - [version](https://github.com/bower/spec/blob/master/json.md#version)

**Comment by LukaszDev** [comment]
😃

**Comment by brinley** [comment]
@LukaszDev Please check if the latest release works well. Thanks

**Comment by LukaszDev** [comment]
Everything works well :) Thanks @Brinley.
