### ISSUE TITLE
Base30 standard

### ISSUE THREAD

**Issue by pjebs** [brinley/jSignature#123]
Is there any clear documentation of how the base30 standard works? I want to port the code to objective c or swift

**Comment by brinley** [comment]
Please check out all the implementations as some are pretty well commented.

https://github.com/brinley/jSignature/blob/master/src/plugins/jSignature.CompressorBase30.js
https://github.com/brinley/jSignature/blob/master/extras/SignatureDataConversion_dotNet/src/SignatureDataConversion/converter_alphanum_base30.cs
https://github.com/brinley/jSignature/blob/master/extras/SignatureDataConversion_PHP/core/jSignature_Tools_Base30.php
https://github.com/brinley/jSignature/blob/master/extras/SignatureDataConversion_Ruby/j_signature_base30.rb

**Comment by pjebs** [comment]
How much would you charge to explain the base30 encoding standard in psuedocode or something easier to understand so I can port it to swift or objective c and the share it in this repo?
