### ISSUE TITLE
jSignature.min.noconflict.js and jSignature.min.js aren't updated in release

### ISSUE THREAD

**Issue by jaredatch** [brinley/jSignature#124]
Both say they are still from 2013 so it looks like they have no been updated with the past releases?

**Comment by aschwartz-satcom** [comment]
+1
especially annoying since compilation of this project is non-trivial

**Comment by jaredatch** [comment]
Ended up going with a different library all together https://github.com/szimek/signature_pad

**Comment by brinley** [comment]
Apologies for the delay, those files have now been updated
