### ISSUE TITLE
jSignature causing fake clicks?

### ISSUE THREAD

**Issue by laDanz** [brinley/jSignature#129]
Use a Windows Tablet with Chrome.
I use ASUS VivoTab Note 8 with Chrome Version 56.0.2924.87 on Windows 10 Home.
Second device with same behaviour: ASUS Transformer Book T100H, same Windows, same Chrome.
Use touch events only(use fingers instead of stylus).

See [Fiddle](https://jsfiddle.net/r8uje1v0/17/) to reproduce:
Step 1) Open select and select a value (i found the third one 'lucky') -> working normal
Step 2) Draw a line into the signature field
Step 3) repeat step 1. At some point you will notice an additional fake click in the upper left of your browser(right around the jsfiddle menu). If you are lucky, you can select an item from the jsfiddle menu just by clicking into the select. -> select is "broken"
Step 4) It's possible you have to restart your browser to reset the bug. It seems it survives new "Runs" from jsfiddle.

Anyone got any idea what could cause this behaviour, or how to fix it?
With Samsung Android Tablet(and Chrome "mobile Browser") the bug could not be reproduced.

**Comment by brinley** [comment]
Can you see if its a device issue?

http://www.transformerforums.com/forum/windows-10-help-discussion-all-asus-ms-powered-transformer-tablet-models/49171-how-fix-ghost-touch-windows-10-a.html

**Comment by laDanz** [comment]
I followed the instructions, turned off "fast startup", rebooted and had the same issues as mentioned.

Must be something different...

**Comment by laDanz** [comment]
The issue seams to be resolved with the new Chrome version 58. On tests i could reproduce it with a snapshot of the Chrome 56 version (https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win/433056/), but no longer with the new version 58.

Issue can be closed.
