### ISSUE TITLE
MVC C#?

### ISSUE THREAD

**Issue by JohnnyBmore** [brinley/jSignature#136]
Hi, I've been trying to add jsignature to my MVC5 C# web app.  I can't get your code to work.  Do you have an example of the code that will work in MVC?  Would it be possible to post your project for download so I could look a how you implemented it? Thank you.

**Comment by brinley** [comment]
The current samples are in https://github.com/brinley/jSignature/tree/master/extras 
Thats all thats available, feel free to contribute your sample.
