### ISSUE TITLE
Save signature on serverside ?

### ISSUE THREAD

**Issue by nottosave** [brinley/jSignature#14]
I'm trying to save a signature on the server side after returning a Base30 string from a mobile device via jquery mobile.

I tried using the function GetData to convert the signature to save as a PNG image, but how should i get the int[][][] to a saved image in the filesystem?
Can anyone give me a C# exampel of how to do this?

Thanks!!

GetData from jSignature.Tools
public int[][][] GetData(string data)

 /// Returns a .net-specific array of arrays structure representing a single signature stroke
        /// A compressed string like this one: 
        ///  "3E13Z5Y5_1O24Z66_1O1Z3_3E2Z4"
        /// representing this raw signature data: 
        ///  [{'x':[100,101,104,99,104],'y':[50,52,56,50,44]},{'x':[50,51,48],'y':[100,102,98]}]
        /// turns into this .Net-specific structure (of array or arrays of arrays)
        ///  [[[100,50],[1,2],[3,4],[-5,-6],[5,-6]], [[50,100],[1,2],[-3,-4]]]

**Comment by EzzatEissa** [comment]
How can i do it by using Java?
i want to convert JSignature Base30 into image or base64 at serverside by using Java
