### ISSUE TITLE
Issue with dyamic resizing on hidden container: height is wrong.

### ISSUE THREAD

**Issue by ryangriggs** [brinley/jSignature#151]
If jSignature is applied to a hidden container (i.e. a modal dialog, etc), the jSignature initialization routine does not take into account the final height of the container, thus rendering the signature box as small height as possible.

However, if you make the hidden container visible first, then apply $("#signature").jSignature(), the height of the signature box matches the container.

**Comment by brinley** [comment]
Have you tried having a container with fixed height within the modal container that is toggled?
Otherwise you might need to initialise jSignature after the modal is made visible

**Comment by ryangriggs** [comment]
Yes, that is the workaround I had to do in order for things to fit properly
in the vertical dimension.  I was just hoping there was an alternative that
would allow me to apply the jSignature before the dialog box became visible.


- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Ryan Griggs
Hilltop Computing
www.hilltop.net
859-328-3223
Toll Free: 1 (888) 5-HILLTOP (888-544-5586)

**Comment by brinley** [comment]
Apart from the two alternatives that I mentioned before,

1) initialise when modal is visible
2) set fixed height on the signature container
3) initialise modal whenever but call jSignature resize when modal is visible
