### ISSUE TITLE
Issue using finger on touch screen with new update in windows 10

### ISSUE THREAD

**Issue by guylap** [brinley/jSignature#157]
Hello, there seems to be an issue when using the finger on some laptop Dell Latitude 3189 touch screen.
It started on some of my clients, probably because a Windows 10 update...
When using finger, it does not write the signature. Works only with the mouse.
I have tried with jqSignature and it works but jqSignature does not have base30 to export and I would like to keep using jSignature.
Any ideas what is going on ?
Thanks

**Comment by brinley** [comment]
What browser is giving issues?
Did you try on multiple browsers?
Can you try http://brinley.github.io/jSignature on different browsers?

**Comment by guylap** [comment]
Hello,
I have tried with Chrome (Latest update) and Microsoft Edge on Windows 10 1803 latest update.
They both did not work with the touchsreen, only with mouse...

Thanks

**Comment by guylap** [comment]
Also, I have tried with Ipad and Iphone using Chrome and they both work with finger.
Seems to be only with Windows 10...
Thanks

**Comment by geland** [comment]
Strangely enough, if I turn on device emulation in chrome on the MS Surface, then touch-and-drag to sign works. Perhaps the emulation mode still uses a different/older way of handling touch events?

**Comment by brinley** [comment]
I don't have a Windows 10 touch screen to test with.

Can you please check if window.navigator.msPointerEnabled returns different values in device emulation mode vs the non working mode?

**Comment by bkdotcom** [comment]
`window.navigator.msPointerEnabled` is `undefined` for both

**Comment by geland** [comment]
In Chrome `window.navigator.msPointerEnabled` is `undefined` in emulation and non-emulation mode.

Another fun fact: If I turn on emulation in Chrome, and then turn off emulation mode, it works for the current page session. After page load while emulation mode is off returns it to a non-working state.

There are some folks complaining about drag-and-drop features no longer working after the recent Windows update - perhaps this could be related? https://social.msdn.microsoft.com/Forums/en-US/99525cc5-9b80-4c18-b81b-d36703a701a0/after-windows-1803-update-icopyhookcopycallback-pszdestfile-parameter-comes-empty?forum=windowsgeneraldevelopmentissues

**Comment by kcloud99** [comment]
I just diff-ed the `window.navigator` object between Firefox(working), Chrome(not working), Chrome in emulation mode(working), and Edge(not working). The only real differences I could find are:
1. Only Chrome (non-emulation mode) has any info in the "mimeTypes" array.
2. userAgent is slightly different
3. msManipulationViewsEnagled: true => Only shows up on Edge browser
4. maxTouchPoints
  -Chrome (non-emulation): 10
  -Chrome(emulation): 1
  -Firefox: 0
  -Edge: 10

**Comment by bkdotcom** [comment]
`canvas.ontouchstart = function(e) {}`  doesn't appear too function
however
canvas.AddEventListener('touchstart', function(e) {}` does work

**Comment by guylap** [comment]
Great !
Thanks to everyone that participated.
Everything is working fine with this fix.

**Comment by brinley** [comment]
@guylap @bkdotcom Can you guys please help test https://github.com/brinley/jSignature/pull/159 and i can merge and do a new release.

**Comment by guylap** [comment]
On my side, everything is working fine with this fix for all my users.
They mostly use Chrome.
Thanks

**Comment by brinley** [comment]
Would appreciate feedback from more testers as I dont have a Windows 10 touch device to test this with. If no issues are called out, I will merge and do a release this weekend

**Comment by brinley** [comment]
#159 has been merged and released as [v2.1.3](https://github.com/brinley/jSignature/releases/tag/v2.1.3)
