### ISSUE TITLE
Drawing Area does not rotate when body is rotated 90 degrees

### ISSUE THREAD

**Issue by oliverseimo** [brinley/jSignature#163]
Hi,

I'm forcing the site to be shown in landsape-mode by using a media query:
`@media only screen and (orientation:portrait)`
Within that query i tell the body to rotate 90 degrees:
`transform: rotate(90deg)`
This works fine and the site is shown in landscape mode only. 
The canvas too.

But the drawing area itself did not rotate.

How can I rotate the drawing area as well?

Thank you for your help.

**Comment by brinley** [comment]
Unfortunately, rotating with css transform is unlikely to tell the JavaScript side that it has rotated.

Short of adding logic to the mouse coordinates that takes into account the rotation.
Not sure if this will work but try
- css transform the canvas -90deg when you transform the body 90deg
- On rotate, reinitialise jSignature with dimensions matching your default mode something like $("#signature").jSignature({width:200,height:300})

**Comment by brinley** [comment]
Yup, use updateSetting to set lineWidth to 0px or null IIRC

**Comment by oliverseimo** [comment]
Tank You
