### ISSUE TITLE
jSignature不是函数

### ISSUE THREAD

**Issue by zichen27** [brinley/jSignature#178]
我在vue文件引入下面三个文件
<script src="./components/jquery.js"></script>
<script src="./components/flashcanvas.js"></script>
<script src="./components/jSignature.min.js"></script>

在mounted里$("#signature").jSignature({height:300,color:"#000",lineWidth:4});  
就报错$(...).jSignature is not a function
请问是什么原因啊

**Comment by brinley** [comment]
Try https://codepen.io/nickamor/pen/XZPBmZ
