### ISSUE TITLE
Ctrl+Z plugin

### ISSUE THREAD

**Issue by utilmind** [brinley/jSignature#184]
It's not an issue, just informing that I have added CtrlZ plugin, which can be used to undo last drawing action on Escape or Ctrl+Z keyboard keys.

It's based on code from UndoButton plugin, but invisible.

https://github.com/utilmind/jSignature/blob/master/src/plugins/jSignature.CtrlZ.js

I would be even more cool if this plugin can be canonical.

**Comment by brinley** [comment]
Sure, submit a PR, I'll have a look at merging
