### ISSUE TITLE
Provide build details?

### ISSUE THREAD

**Issue by jmenashe** [brinley/jSignature#185]
The wscript file doesn't work with my version of waf and documentation is nearly non-existant. Can you provide some basic instructions for building?

**Comment by brinley** [comment]
Sorry the build process is antiquated and needs to be upgraded to something more modern

I've attached a version of wak that works. Unzip in the root directory and run `python wak.py`

[wak.py.zip](https://github.com/brinley/jSignature/files/5035033/wak.py.zip)
