### ISSUE TITLE
Jsignature on IE10 touch mode

### ISSUE THREAD

**Issue by kakons** [brinley/jSignature#29]
Hi, I'm trying to use jsignature on ie10 with touch screen, touch move events not recognized.

Any way to work only with flash canvas instead of html5 ?

Will you support Ie10 on touch screen ?

Thank's head 

Shlomi

**Comment by xacaxulu** [comment]
+1

This worked: 

#signatureDiv{
-ms-touch-action: none;
}

**Comment by MickL** [comment]
jSignature is still not working on Surface using IE Edge. -ms-touch-action: none; makes no difference.
