### ISSUE TITLE
Jsignature bootstrap modal

### ISSUE THREAD

**Issue by asoet** [brinley/jSignature#49]
Jsignature doesn't work in the bootstrap 3 modal view. 
Is this true?

$("#AddSignatureModal").on('show.bs.modal', function () {
            $("#signature").jSignature();
            
        })

**Comment by brinley** [comment]
The stackoverflow post above seems to have a valid solution

$('#myModal').on('show.bs.modal', function (e) {    
  $("#signature").jSignature();
  $("#signature").resize();
});
