### ISSUE TITLE
Urgent!!!Can anyone help with the iPad problem

### ISSUE THREAD

**Issue by mxu0422** [brinley/jSignature#70]
When I apply the jSignature plugin to the iPad app, the iPad shows two line, two canvas, but I just need one canvas, anyone can help me remove the second line there? Thank you!

![img_9539](https://cloud.githubusercontent.com/assets/7784412/5033868/29101b4c-6b40-11e4-9bcf-01e16a2f6dd7.JPG)

Here is the code:
<script type="text/javascript" src="../shared/js/jquery.js"></script>
		<script type="text/javascript" src="../shared/js/jSignature.min.js"></script>
		<script type="text/javascript">
			jQuery(document).ready(function($) {
				var $sigdiv = $("#signature");
				$sigdiv.jSignature();
			
			});
		</script>		
			<div style="-webkit-border-radius: 10px 10px 0 0;border-radius: 10px 10px 0 0;text-align: left;color: #fff;background-color: #8c8c8c; font-size: 20px;text-shadow: none !important;font-weight: normal;padding: 15px; font-weight: lighter">Signature</div>
			<div id="signature" ></div>

**Comment by almogdesign** [comment]
Hi, your creating the jSignature twice, double check your code also try the following 

  $("#signature").jSignature();
