### ISSUE TITLE
image/jSignature;base30 undefined 

### ISSUE THREAD

**Issue by almogdesign** [brinley/jSignature#79]
If have the following - var signature = $("#signature").jSignature("getData", "image/jSignature;base30");
I get undefined 

this works fine -  var signature = $("#signature").jSignature("getData", "base30");

**Comment by escapedcat** [comment]
Why do you use the first one though? Is this expected to work?
I just found the second one in the docs.

**Comment by almogdesign** [comment]
@escapedcat no for some reason I thought alias can also be used as the string option. My mistake

**Comment by escapedcat** [comment]
Cool ;)
