### ISSUE TITLE
API "destroy" event?

### ISSUE THREAD

**Issue by donluz** [brinley/jSignature#87]
Is there any way to destroy the jSignature object?  I cannot find in the API doc, but may be missing something.  Right now I am having to rely on "typeof == undefined" and init jSig or not.

**Comment by MickL** [comment]
Maybe use .jSignature('disable')?

**Comment by donluz** [comment]
Good thought, but it won't work as intended.  All this call does is make it so the element cannot be written on.  The "destroy" would actually remove the object in memory, clear its pointer, etc and could then be re-created from scratch entirely unrelated to a prior existing one.

**Comment by ianpogi5** [comment]
+1

**Comment by zspitzer** [comment]
This doesn't seem to completely cleanup after itself,  in Chrome Dev Tools I'm seeing a reference to jSignature.parentresized under a Detached DOM tree
