### ISSUE TITLE
Saving to Server C# .Net

### ISSUE THREAD

**Issue by warrenla** [brinley/jSignature#89]
I am fairly sure this is not an issue, but I am finding the documentation a bit confusing on how to take the output of the jSignature and work with it on the server.  

I have the data being passed to my server via a simple webmethod.
Here I grab the string and do a bit of work with it. Unfortunately, the reporting tool we use does not support SVG format so I must convert it to a jpeg, gif, png or such... 

Here is an exmaple of the code
  [WebMethod(EnableSession = true)]
        public int SaveSignature(string entityUID, string entityTypeUID, string sig)
        {
            var SaveSignature = sig;
            
            string[] image = SaveSignature.Split(Convert.ToChar(","));
            SaveImage(image[1]);

            return -1;

        }

  public void SaveImage(string base64)
        {

            byte[] bytes = Convert.FromBase64String(base64);

            Image image;
            using (MemoryStream ms = new MemoryStream(bytes))
            {
                image = Image.FromStream(ms);
            }
            var filePath = "D:\\SourceControl\\Hayes IT\\NEXT\\TIPWebITApp\\TIPWebIT\\Attachment\\" + "ImageName.jpg";
            image.Save(filePath, System.Drawing.Imaging.ImageFormat.Gif);
        
          
        }

I get a parameter missing from the Image.FromStream method.. 
Here is the SVG data from jsignature:
data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+PCFET0NUWVBFIHN2ZyBQVUJMSUMgIi0vL1czQy8vRFREIFNWRyAxLjEvL0VOIiAiaHR0cDovL3d3dy53My5vcmcvR3JhcGhpY3MvU1ZHLzEuMS9EVEQvc3ZnMTEuZHRkIj48c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmVyc2lvbj0iMS4xIiB3aWR0aD0iNTAxIiBoZWlnaHQ9IjEzMyI+PHBhdGggZmlsbD0ibm9uZSIgc3Ryb2tlPSIjMDAwMDAwIiBzdHJva2Utd2lkdGg9IjIiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIgZD0iTSAxIDcgYyAwLjMyIDAuMDUgMTIuMTYgMS42NSAxOCAzIGMgMi43MyAwLjYzIDUuMzggMS43NyA4IDMgYyA4LjIyIDMuODUgMTUuNjYgOC4xMiAyNCAxMiBjIDYuNDEgMi45OCAxMi42NiA0LjkzIDE5IDggYyAxNC44NiA3LjE5IDI3Ljk5IDE0Ljc0IDQzIDIyIGMgMTYuNDEgNy45MyAzMS43OCAxNS4wMSA0OCAyMiBjIDMuMjEgMS4zOCA2Ljc1IDEuNzMgMTAgMyBjIDQuNDYgMS43NCA4LjQ5IDQuMzcgMTMgNiBjIDcuNTcgMi43MyAxNS40MyA0LjI3IDIzIDcgYyA0LjUxIDEuNjMgOC41MSA0LjQxIDEzIDYgYyA2Ljg1IDIuNDIgMTQuMSAzLjU3IDIxIDYgYyA1LjUyIDEuOTQgMTAuNjggNC45NyAxNiA3IGwgNSAxIi8+PHBhdGggZmlsbD0ibm9uZSIgc3Ryb2tlPSIjMDAwMDAwIiBzdHJva2Utd2lkdGg9IjIiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIgZD0iTSA5MiAxMTggYyAwLjYxIC0wLjQ5IDIyLjg0IC0xOS4yNSAzNSAtMjggYyA2LjkzIC00Ljk5IDE0LjI2IC04Ljk4IDIyIC0xMyBjIDE4LjU2IC05LjY0IDM2LjkyIC0xNy4yNSA1NSAtMjcgYyA3LjQ1IC00LjAyIDE0LjM1IC05LjA3IDIxIC0xNCBjIDIuMjQgLTEuNjYgMy45MSAtNC40OCA2IC02IGMgMS4zMyAtMC45NyAzLjczIC0wLjk0IDUgLTIgYyA2LjE5IC01LjE2IDE5IC0xOCAxOSAtMTgiLz48cGF0aCBmaWxsPSJub25lIiBzdHJva2U9IiMwMDAwMDAiIHN0cm9rZS13aWR0aD0iMiIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiBkPSJNIDIwMSA0IGMgMC4xNiAwLjExIDYuMTggMy43MiA5IDYgYyA1LjkxIDQuNzcgMTEuMDEgMTAuMSAxNyAxNSBjIDUuMjggNC4zMiAxMC4zNSA4LjAyIDE2IDEyIGMgMTUuNDMgMTAuODggMjkuMjggMjEuMTMgNDUgMzEgYyAxMy41MyA4LjQ5IDI3LjE1IDE1LjgxIDQxIDIzIGMgMy40NSAxLjc5IDcuNjUgMi4zMyAxMSA0IGMgMi40NiAxLjIzIDQuNzEgNC4yNCA3IDUgYyAyLjEzIDAuNzEgNS45IC0wLjgyIDggMCBjIDMuMjEgMS4yNSA2LjczIDUuMjUgMTAgNyBjIDEuMzcgMC43MyAzLjQ4IDAuNDEgNSAxIGMgMi42NyAxLjAzIDUuMjggMy4xNCA4IDQgbCAxMSAyIi8+PHBhdGggZmlsbD0ibm9uZSIgc3Ryb2tlPSIjMDAwMDAwIiBzdHJva2Utd2lkdGg9IjIiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIgZD0iTSA0NTAgMSBjIC0wLjM4IDAuMzUgLTE0LjY2IDEzLjk3IC0yMiAyMCBjIC0xLjY2IDEuMzYgLTQuMjIgMS43MiAtNiAzIGMgLTYuNDMgNC42MyAtMTIuNTIgMTAuNDQgLTE5IDE1IGMgLTIuMzkgMS42OCAtNS42IDIuNCAtOCA0IGMgLTIuNDggMS42NSAtNC41NyA0LjcxIC03IDYgYyAtMi4xNyAxLjE2IC01Ljc3IDAuNzggLTggMiBjIC00LjY1IDIuNTQgLTkuMTkgNy4wNyAtMTQgMTAgYyAtMi43NiAxLjY4IC02LjM3IDIuMjQgLTkgNCBjIC01LjE0IDMuNDIgLTkuODUgOC40MiAtMTUgMTIgYyAtMi40IDEuNjcgLTUuNDMgMi40NCAtOCA0IGMgLTUuMTggMy4xNSAtMTAuMDYgNi4zOSAtMTUgMTAgYyAtMy44OSAyLjg0IC03LjA4IDYuNDMgLTExIDkgYyAtNS42OSAzLjczIC0xMi4yIDYuMzUgLTE4IDEwIGMgLTMuMjEgMi4wMiAtNi4wNSA1LjE5IC05IDcgYyAtMS4wNyAwLjY2IC0yLjgzIDAuNDIgLTQgMSBjIC0zLjMxIDEuNjUgLTcuMTUgMy43NiAtMTAgNiBjIC0xLjU2IDEuMjMgLTIuNTggMy45MyAtNCA1IGwgLTQgMSIvPjxwYXRoIGZpbGw9Im5vbmUiIHN0cm9rZT0iIzAwMDAwMCIgc3Ryb2tlLXdpZHRoPSIyIiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIGQ9Ik0gMzE3IDIxIGMgMC40NiAwLjIzIDE3Ljc1IDcuOTQgMjYgMTMgYyAxMC43OCA2LjYyIDIwLjIgMTUgMzEgMjIgYyA3LjUxIDQuODYgMTUuMDMgOS43NiAyMyAxMyBjIDExLjM2IDQuNjIgMjQuMTkgNi45NyAzNiAxMSBjIDIuODEgMC45NiA1LjIxIDIuODggOCA0IGMgNS42MyAyLjI1IDExLjMyIDQuMzQgMTcgNiBjIDIuMjMgMC42NSA0LjgzIDAuMzEgNyAxIGMgMy45OSAxLjI2IDguMDIgNC4yMyAxMiA1IGMgNS44MyAxLjEzIDEzLjI2IDAuMjUgMTkgMSBsIDQgMiIvPjxwYXRoIGZpbGw9Im5vbmUiIHN0cm9rZT0iIzAwMDAwMCIgc3Ryb2tlLXdpZHRoPSIyIiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIGQ9Ik0gNDk0IDE4IGMgLTAuMDcgMC4wNyAtMi44OCAyLjU2IC00IDQgYyAtMS4xNiAxLjQ5IC0xLjgyIDMuNjUgLTMgNSBjIC0xLjAxIDEuMTUgLTMuMDEgMS43OCAtNCAzIGMgLTMuMTMgMy44NiAtNS42OSA4LjgyIC05IDEzIGMgLTQuNDYgNS42MiAtOS4xIDEwLjg2IC0xNCAxNiBjIC0yLjEzIDIuMjMgLTQuOTQgMy43MyAtNyA2IGMgLTcuNiA4LjM4IC0xNC40IDE3LjIzIC0yMiAyNiBjIC0xLjI2IDEuNDYgLTIuNTYgMi44OCAtNCA0IGMgLTEuNDkgMS4xNiAtMy42NCAxLjc3IC01IDMgYyAtMi4xNCAxLjk1IC0zLjg2IDUuMDUgLTYgNyBjIC0xLjM2IDEuMjMgLTMuNjUgMS43MiAtNSAzIGMgLTQuNzUgNC41IC05LjggMTAuMDEgLTE0IDE1IGMgLTAuOTIgMS4wOSAtMS4wNCAzLjE0IC0yIDQgbCAtOCA1Ii8+PC9zdmc+

**Comment by warrenla** [comment]
Resolved

**Comment by saeedht** [comment]
Hi Warrenla,

I am facing the same issue. Can you please let me know how did you resolve? The JSignature is storing image data in base64 & base30 and I need to convert this back to image file so that I could pass that in crystal reporting.

Any help regarding this would be highly appreciated. 
Thank you.
