### ISSUE TITLE
JSignature adding default junk data

### ISSUE THREAD

**Issue by avishekroychowdhury** [brinley/jSignature#93]
Hi, 
I am getting the below default junk string while rendering from one Form(which has a textbox which captures JSignature ) and trying to save the data:
iVBORw0KGgoAAAANSUhEUgAAAWIAAABZCAYAAAAEli6gAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAC0SURBVHhe7cexDYAwDABBmwlpGCFTZYVIjGgarxCB0F3z+gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHhFdrcbY9yZefYCfFpVrTnn1bvV0QUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIA/ingA9UMIBDkEGOQAAAAASUVORK5CYII=

I believe it's base64 encoded string.
Any idea on this?
Thanks,
Avishek

**Comment by brinley** [comment]
Its probably base30 not base64. Try checking that first.
