### ISSUE TITLE
Microsoft Edge / IE11

### ISSUE THREAD

**Issue by CBlampied** [brinley/jSignature#95]
Using jSignature for field engineer application - really excellent plug-in!

Noticed issue on Windows 10/MS Edge browser similar to previous issues reported on Windows 8/8.1 where adding -ms-touch-action: none; to the container <div> was the solution.

It appears that this is deprecated in IE11/Edge, being replaced by the non-prefixed touch-action: none;

https://msdn.microsoft.com/en-us/library/windows/apps/hh767313.aspx?f=255&MSPPError=-2147217396

Hope this helps someone.

**Comment by mattcrwi** [comment]
I can confirm this issue and fix for MS Edge. Thanks, CBlampied.

**Comment by brinley** [comment]
Hi, can either of you confirm if https://github.com/brinley/jSignature/pull/109 fixes the issue?

**Comment by MickL** [comment]
I can confirm the fix is working on Surface using Win 10 + Edge! THANKS ! :)

**Comment by brinley** [comment]
Thanks @MickL

**Comment by PIlepRusel** [comment]
Did you replicate the issue on Microsoft Edge Chrome ?
